force-app/main/default/objects/TimelineView__mdt/TimelineView__mdt.object-meta.xml
<CustomObject>
    <label>Timeline View</label>
    <pluralLabel>Timeline Views</pluralLabel>
</CustomObject>

force-app/main/default/objects/TimelineView__mdt/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Mark record for testing. The record won&apos;t be displayed as a picklist alternative.</inlineHelpText>
    <label>Test</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TimelineViewPicklist.cls
public with sharing class TimelineViewPicklist extends VisualEditor.DynamicPickList {

    VisualEditor.DesignTimePageContext context;
    
    public TimelineViewPicklist(VisualEditor.DesignTimePageContext context) {
        this.context = context;
    }

    public override VisualEditor.DataRow getDefaultValue(){
        VisualEditor.DataRow defaultValue = new VisualEditor.DataRow('View All', 'ALL');
        return defaultValue;        
    }

    public override VisualEditor.DynamicPickListRows getValues() {
        VisualEditor.DynamicPickListRows  myValues = new VisualEditor.DynamicPickListRows();
        myValues.addRow(this.getDefaultValue());

        for (TimelineView__mdt record : TimelineView__mdt.getAll().values()) {
            if (!record.Test__c || Test.isRunningTest()) {
                myValues.addRow(new VisualEditor.DataRow(record.MasterLabel, record.DeveloperName));
            }
        }
        return myValues;
    }    
}